# Generated by Django 3.1.4 on 2021-01-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collection',
            field=models.BooleanField(null=True),
        ),
    ]
