# Generated by Django 3.1.4 on 2021-01-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='collection',
            field=models.BooleanField(),
        ),
    ]
