# Generated by Django 3.1.4 on 2021-01-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210111_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='collection',
        ),
    ]
